#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

# ── Version metadata ──────────────────────────────────────────────
VERSION=$(cat VERSION 2>/dev/null || echo "1.0.0")

# Auto-increment patch version on every build
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
PATCH=$((PATCH + 1))
VERSION="$MAJOR.$MINOR.$PATCH"
echo "$VERSION" > VERSION

BUILD_FILE=".build-number"

if [ -f "$BUILD_FILE" ]; then
    BUILD=$(cat "$BUILD_FILE")
    BUILD=$((BUILD + 1))
else
    BUILD=1
fi
echo "$BUILD" > "$BUILD_FILE"

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Generate Sources/Version.swift ─────────────────────────────────
cat > Sources/Version.swift <<SWIFTEOF
// AUTO-GENERATED by build.sh — do not edit manually
// Version:  $VERSION
// Build:    $BUILD
// Git:      $GIT_HASH
// Date:     $BUILD_DATE

struct VersionInfo {
    static let version   = "$VERSION"
    static let build     = "$BUILD"
    static let gitHash   = "$GIT_HASH"
    static let buildDate = "$BUILD_DATE"

    static func string() -> String {
        "G2 Convert \\(version) (build \\(build)) [\\(gitHash)] \\(buildDate)"
    }

    static func shortString() -> String {
        "v\\(version) b\\(build) (\\(gitHash))"
    }
}
SWIFTEOF

# ── Update Info.plist ─────────────────────────────────────────────
PLIST="G2Convert.app/Contents/Info.plist"
if [ -f "$PLIST" ]; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$PLIST" 2>/dev/null || true
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD"           "$PLIST" 2>/dev/null || true
    /usr/libexec/PlistBuddy -c "Add :NSHumanReadableCopyright string 'G2 Convert $VERSION ($BUILD) — © Gael Abegg Gauthey — $BUILD_DATE'" "$PLIST" 2>/dev/null || \
    /usr/libexec/PlistBuddy -c "Set :NSHumanReadableCopyright 'G2 Convert $VERSION ($BUILD) — © Gael Abegg Gauthey — $BUILD_DATE'" "$PLIST" 2>/dev/null || true
fi

# ── Build ──────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  G2 Convert  v$VERSION  build $BUILD"
echo "║  git: $GIT_HASH"
echo "║  date: $BUILD_DATE"
echo "╚══════════════════════════════════════════════════╝"
echo ""

echo "→ swift build -c release"
swift build -c release

echo ""
echo "→ Copying binary to .app bundle"
cp .build/release/G2Convert "G2Convert.app/Contents/MacOS/G2Convert"

echo ""
echo "✓ Build complete"
echo "  Binary:  $(stat -f%z .build/release/G2Convert) bytes"
echo "  Bundle:  G2Convert.app/"
echo "  Version: $VERSION ($BUILD)"
echo "  Try:     open G2Convert.app"
echo "  Or:      .build/release/G2Convert --version"
echo ""
