// AUTO-GENERATED by build.sh — do not edit manually
// Version:  1.0.13
// Build:    20
// Git:      925f5b1
// Date:     2026-06-10T18:47:02Z

struct VersionInfo {
    static let version   = "1.0.13"
    static let build     = "20"
    static let gitHash   = "925f5b1"
    static let buildDate = "2026-06-10T18:47:02Z"

    static func string() -> String {
        "G2 Convert \(version) (build \(build)) [\(gitHash)] \(buildDate)"
    }

    static func shortString() -> String {
        "v\(version) b\(build) (\(gitHash))"
    }
}
