// AUTO-GENERATED by build.sh — do not edit manually
// Version:  1.0.0
// Build:    5
// Git:      7fb5202
// Date:     2026-06-10T16:49:53Z

struct VersionInfo {
    static let version   = "1.0.0"
    static let build     = "5"
    static let gitHash   = "7fb5202"
    static let buildDate = "2026-06-10T16:49:53Z"

    static func string() -> String {
        "G2 Convert \(version) (build \(build)) [\(gitHash)] \(buildDate)"
    }

    static func shortString() -> String {
        "v\(version) b\(build) (\(gitHash))"
    }
}
